### ISSUE TITLE
Redirect services

### ISSUE THREAD

**Issue by drgomesp** [KnpLabs/FriendlyContexts#176]
Is it possible to redirect services such as this one:

```yaml
friendly.page.resolver:
      class: AppBundle\Page\Resolver\MyResolver
      arguments:
          - "Page"
```
