### ISSUE TITLE
Replace Alice fixtures dependencies to import in yml files

### ISSUE THREAD

**Issue by spolischook** [KnpLabs/FriendlyContexts#198]
It will decrease configuration complexity and move responsibility of fixture dependencies in one place - yml fixtures itself

``` yml
imports:
  - ../../path/to/users.yml

Acme\Entity\Product:
  product-{1..30}:
    title: <sentence()>
    owner: @user-*
```
