### ISSUE TITLE
EntityContext: Manage multiple connections

### ISSUE THREAD

**Issue by Soullivaneuh** [KnpLabs/FriendlyContexts#222]
According to [this part of code](https://github.com/KnpLabs/FriendlyContexts/blob/232625f11290c3ce0355860fc539d09f623d9da9/src/Knp/FriendlyContexts/Context/EntityContext.php#L38), it seems you always call the default entity manager for this context.

It would be great to be able to specify which connection to use when we have multiple ones, like this:

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                driver_class: AppBundle\DBAL\Driver
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                # TODO: Remove it when vendor issue will be solved
                # See https://github.com/sonata-project/SonataAdminBundle/issues/3342
                server_version: 5.6

            powerdns:
                driver:   pdo_mysql
                driver_class: AppBundle\DBAL\Driver
                host:     '%powerdns_host%'
                port:     '%powerdns_port%'
                dbname:   '%powerdns_name%'
                user:     '%powerdns_user%'
                password: '%powerdns_password%'
                charset:  UTF8
                server_version: 5.6
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager:   default
        entity_managers:
            default:
                connection:           default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: AppBundle\Repository\DefaultRepository
                mappings:
                    AppBundle: ~
                    FOSUserBundle: ~
                    FOSOAuthServerBundle: ~
            powerdns:
                connection:           powerdns
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: AppBundle\Repository\DefaultRepository
                mappings:
                    PowerDNSBundle: ~
```
