### ISSUE TITLE
Testing symfony API always return 403

### ISSUE THREAD

**Issue by vitoo** [KnpLabs/FriendlyContexts#255]
Hello,

Every request done by behat got a 403 response, in the example bellow, the url works on a web browser : 

GET http://localhost:8000/web/app_test.php/api/search/users?fullName=Baratheon

Do you have any clue ? Thanks you !

behat.yml
```yml
default:
    suites:
        default:
            paths:
                - "%paths.base%/features"
            contexts:
                - ApiContext: ~

    extensions:
        Knp\FriendlyContexts\Extension:
            api:
                base_url: "http://localhost:8000/web/app_test.php"

```

user.feature
```feature
Feature: Search User entities

    Scenario: I can search User entities
        Given I prepare a GET request on "/api/search/users?fullName=Baratheon"
        When I send the request
        Then I should receive a 200 response
        And the response should contain the following json:
            """
            [
              {
                "id": 1,
                "firstName": "Robert",
                "lastName": "Baratheon",
                "email": "admin@extreme.com",
                "latitude": null,
                "longitude": null,
                "language": null
              }
            ]
            """
```

Result : 

      Expecting response code to be "200" but "403" given (Exception)
